# Generated by Django 2.1.1 on 2019-03-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Persons',
        ),
    ]
