# Generated by Django 2.1.1 on 2019-03-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20190307_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
